parameters:
    secret: ThisTokenIsNotSoSecretChangeIt
    
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # INSTALLER
    #
    Pimcore\Bundle\xTemplateBundlex\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcorexTemplateBundlex')"

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Pimcore\Bundle\xTemplateBundlex\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]