services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $studioUrlUrlPath: '%pimcore_studio_ui.url_path%'
            $studioMercureClientUrl: '%pimcore_studio_backend.mercure_settings.hub_url_client%'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Pimcore\Bundle\StudioUiBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    Pimcore\Bundle\StudioUiBundle\Service\StaticResourcesResolverInterface:
        class: Pimcore\Bundle\StudioUiBundle\Service\StaticResourcesResolver

# add more services, or override services that need manual wiring
#    Pimcore\Bundle\StudioUiBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"
